### Get all compuuters list
GET http://localhost:4000/api/computers/getall

### Get one computer
GET http://localhost:4000/api/computers/getone/1

### Save a computer
POST http://localhost:4000/api/computers/save
Content-Type: application/json

{
    "fk_laboratory":1,
    "serial_number": 3223234423,
    "brand": "Dell",
    "network_type":"Wireless",
    "status": "working",
    "ram_memory": "8 gb",
    "motherboard": "Dell OEM",
    "cpu":"Intel Core i5 ",
    "gpu":"Intel HD Graphics",
    "psu":"300w",
    "storage":"1TB HDD",
    "display":"IPS 1080p 24'",
    "keyboard": "Dell OEM",
    "mouse":"Dell OEM",
    "sound": "Dell twins sound pack"

}

### Update a computer
PUT http://localhost:4000/api/computers/update/1
Content-Type: application/json

{
    "location":"Edificio B"
}

### Delete a computer
DELETE http://localhost:4000/api/computers/delete/2
Content-Type: application/json